apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockprediction
  template:
    metadata:
      labels:
        app: stockprediction
    spec:
      containers:
      - name: cv-app
        image: gcr.io/deploying-apps-403014/app:v1
        ports:
        - containerPort: 8501
